title: Fresh Site
author: Fresh Teacher
email: freshteacheruganda256@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a demo of a git hub page. It will soon replace
# social links
twitter_username: jesse_comedian
github_username:  Fresh-Teacher

show_excerpts: true # set to false to remove excerpts on the homepage
